[package]
name = "subscriber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh.workspace = true
borsh-derive.workspace = true
crosstown_bus.workspace = true
events = { path = "../events" }

